"""
pages/6_Quizzes.py — Quiz Engine (Phase 6)
Generate → Answer → Submit → Results with explanations.
"""

import sys, os, html as html_lib
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

import streamlit as st
from frontend.utils.api_client import APIClient
from frontend.utils.ui import page_header, render_sidebar, require_login

st.set_page_config(page_title="Quizzes — AI Tutor", page_icon="🎯", layout="wide")
require_login()
render_sidebar("quizzes")

for k, v in {"quiz_state":"idle","quiz_attempt_id":None,"quiz_questions":[],
              "quiz_answers":{},"quiz_subject":"","quiz_results":None}.items():
    if k not in st.session_state: st.session_state[k] = v

client = APIClient()

page_header("Adaptive Quizzes", "5-question MCQ quizzes generated for your weak subjects.")

# ═══════════════════════════════════════════════════════════════════
# STATE: idle — Quiz setup screen
# ═══════════════════════════════════════════════════════════════════

if st.session_state.quiz_state == "idle":
    st.markdown("Test your knowledge with a 5-question MCQ quiz. Questions are generated by the Quiz Agent.")
    st.divider()

    # Load subject suggestions
    res_sub = client.get_weak_subjects(st.session_state.user_id)
    weak_subjects = []
    all_subjects  = []
    if res_sub["success"]:
        weak_subjects = res_sub["data"].get("weak_subjects", [])
        all_subjects  = res_sub["data"].get("all_subjects", [])

    col1, col2 = st.columns(2)

    with col1:
        st.markdown("#### Quick Start — Weak Subjects")
        if weak_subjects:
            for subj in weak_subjects:
                if st.button(f"🎯 Quiz on {subj}", key=f"q_{subj}",
                             use_container_width=True, type="primary"):
                    st.session_state.quiz_prefill_subject = subj
                    st.rerun()
        else:
            st.info("Upload a marksheet and run AI Analysis to get subject suggestions.")

    with col2:
        st.markdown("#### Custom Quiz")
        all_opts    = list(dict.fromkeys(weak_subjects + [s for s in all_subjects if s not in weak_subjects]))
        prefill     = st.session_state.get("quiz_prefill_subject","")
        if prefill and prefill in all_opts:
            default_idx = all_opts.index(prefill)
        else:
            default_idx = 0

        if all_opts:
            subject = st.selectbox("Subject:", all_opts, index=default_idx)
        else:
            subject = st.text_input("Subject:", value=prefill, placeholder="e.g. Mathematics")

        difficulty   = st.select_slider("Difficulty:", ["Easy","Medium","Hard"], value="Medium")
        grade_level  = st.selectbox("Level:", ["school","college","university"], index=0)

        if st.button("🚀 Generate Quiz", type="primary", use_container_width=True):
            if not subject:
                st.warning("Please enter a subject.")
            else:
                with st.spinner("Quiz Agent is generating your questions… (~15 seconds)"):
                    res = client.generate_quiz(
                        user_id     = st.session_state.user_id,
                        subject     = subject,
                        difficulty  = difficulty,
                        grade_level = grade_level,
                    )
                if res["success"]:
                    d = res["data"]
                    st.session_state.quiz_state      = "in_progress"
                    st.session_state.quiz_attempt_id = d["attempt_id"]
                    st.session_state.quiz_questions  = d["questions"]
                    st.session_state.quiz_answers    = {}
                    st.session_state.quiz_subject    = subject
                    st.session_state.quiz_results    = None
                    st.session_state.quiz_prefill_subject = ""
                    st.rerun()
                else:
                    st.error(f"❌ {res['error']}")

    # ── Quiz history ──────────────────────────────────────────────
    st.divider()
    st.markdown("#### 📋 Your Quiz History")
    res_hist = client.get_quiz_history(st.session_state.user_id)
    if res_hist["success"]:
        attempts = res_hist["data"].get("attempts", [])
        if attempts:
            for a in attempts[:8]:
                pct = a["percentage"]
                color = "#22c55e" if pct>=70 else ("#f59e0b" if pct>=50 else "#ef4444")
                st.markdown(
                    f'<div style="background:#1e293b;border:1px solid #334155;border-left:4px solid {color};'
                    f'padding:10px 14px;border-radius:0 6px 6px 0;margin-bottom:6px;'
                    f'display:flex;justify-content:space-between;align-items:center;">'
                    f'<span style="color:#f1f5f9;font-weight:600;">{html_lib.escape(str(a["subject"]))}</span>'
                    f'<span style="color:{color};font-weight:700;">{a["score"]}/{a["total"]} ({pct}%)</span>'
                    f'<span style="color:#64748b;font-size:12px;">{a["attempted_at"][:10]}</span>'
                    f'</div>', unsafe_allow_html=True)
        else:
            st.info("No quizzes completed yet. Take your first quiz above!")


# ═══════════════════════════════════════════════════════════════════
# STATE: in_progress — Answer questions
# ═══════════════════════════════════════════════════════════════════

elif st.session_state.quiz_state == "in_progress":
    questions = st.session_state.quiz_questions
    subject   = st.session_state.quiz_subject

    st.markdown(f"### 📝 Quiz: **{subject}**")
    st.caption(f"5 questions · Answer all before submitting · Attempt #{st.session_state.quiz_attempt_id}")
    st.divider()

    answers = st.session_state.quiz_answers.copy()

    for q in questions:
        qid     = str(q["id"])
        options = q["options"]
        opts    = list(options.keys())  # ["A","B","C","D"]
        labels  = [f"{k}: {v}" for k, v in options.items()]

        current_val = answers.get(qid)
        current_idx = opts.index(current_val) + 1 if current_val in opts else 0

        st.markdown(
            f'<div style="background:#1e293b;border:1px solid #334155;border-left:4px solid #6366f1;'
            f'padding:14px 18px 4px 18px;border-radius:0 8px 8px 0;margin-bottom:4px;">'
            f'<span style="color:#818cf8;font-size:12px;font-weight:700;">Q{q["id"]}</span>'
            f'<div style="color:#f1f5f9;font-size:15px;margin-top:4px;">{html_lib.escape(str(q["question"]))}</div>'
            f'</div>', unsafe_allow_html=True)

        choice = st.radio(
            label      = f"q_{qid}",
            options    = ["(not answered)"] + labels,
            index      = current_idx,
            key        = f"radio_{qid}",
            label_visibility = "collapsed",
        )

        if choice != "(not answered)":
            answers[qid] = choice.split(":")[0].strip()
        elif qid in answers:
            del answers[qid]

        st.markdown("")

    st.session_state.quiz_answers = answers
    answered = len(answers)
    total    = len(questions)

    st.divider()
    st.markdown(f"**Answered:** {answered} / {total}")

    c1, c2 = st.columns(2)
    with c1:
        if st.button(f"✅ Submit Quiz ({answered}/{total} answered)",
                     type="primary", use_container_width=True,
                     disabled=(answered < total)):
            with st.spinner("Scoring your quiz…"):
                res = client.submit_quiz(
                    user_id    = st.session_state.user_id,
                    attempt_id = st.session_state.quiz_attempt_id,
                    answers    = answers,
                )
            if res["success"]:
                st.session_state.quiz_results = res["data"]
                st.session_state.quiz_state   = "results"
                st.rerun()
            else:
                st.error(f"❌ {res['error']}")
    with c2:
        if st.button("❌ Cancel Quiz", use_container_width=True):
            st.session_state.quiz_state = "idle"
            st.rerun()

    if answered < total:
        st.caption(f"Please answer all {total} questions before submitting.")


# ═══════════════════════════════════════════════════════════════════
# STATE: results — Show score and explanations
# ═══════════════════════════════════════════════════════════════════

elif st.session_state.quiz_state == "results":
    results = st.session_state.quiz_results
    subject = st.session_state.quiz_subject

    score   = results["score"]
    total   = results["total"]
    pct     = results["percentage"]
    grade   = results["grade"]

    grade_color = {"Excellent":"#22c55e","Good":"#84cc16",
                   "Pass":"#f59e0b","Needs More Practice":"#ef4444"}.get(grade,"#94a3b8")

    st.markdown(
        f'<div style="background:#1e293b;border:1px solid {grade_color};border-radius:12px;'
        f'padding:24px;text-align:center;margin-bottom:20px;">'
        f'<div style="color:{grade_color};font-size:48px;font-weight:700;">{score}/{total}</div>'
        f'<div style="color:{grade_color};font-size:20px;font-weight:600;">{pct}% — {html_lib.escape(grade)}</div>'
        f'<div style="color:#94a3b8;font-size:14px;margin-top:6px;">Quiz: {html_lib.escape(subject)}</div>'
        f'</div>', unsafe_allow_html=True)

    st.markdown("### 📋 Detailed Results & Explanations")

    for r in results["results"]:
        is_correct  = r["is_correct"]
        icon        = "✅" if is_correct else "❌"
        border_col  = "#22c55e" if is_correct else "#ef4444"
        your_ans    = r.get("your_answer","?")
        correct_ans = r["correct_answer"]
        explanation = r.get("explanation","")

        st.markdown(
            f'<div style="background:#1e293b;border:1px solid {border_col};border-radius:8px;'
            f'padding:14px 18px;margin-bottom:10px;">'
            f'<div style="display:flex;align-items:flex-start;gap:10px;margin-bottom:8px;">'
            f'<span style="font-size:18px;">{icon}</span>'
            f'<div style="color:#f1f5f9;font-size:14px;font-weight:500;">{html_lib.escape(str(r["question"]))}</div>'
            f'</div>'
            f'<div style="display:flex;gap:16px;font-size:13px;margin-bottom:8px;">'
            f'<span style="color:#94a3b8;">Your answer: <strong style="color:{"#22c55e" if is_correct else "#ef4444"};">{html_lib.escape(your_ans)}</strong></span>'
            f'{"" if is_correct else f"<span style=\"color:#94a3b8;\">Correct: <strong style=\"color:#22c55e;\">{html_lib.escape(correct_ans)}</strong></span>"}'
            f'</div>'
            f'<div style="background:#0f172a;border-radius:4px;padding:8px 12px;color:#94a3b8;font-size:13px;">'
            f'💡 {html_lib.escape(str(explanation))}'
            f'</div>'
            f'</div>', unsafe_allow_html=True)

    st.divider()
    c1, c2, c3 = st.columns(3)
    with c1:
        if st.button("🔄 Take Another Quiz", use_container_width=True, type="primary"):
            st.session_state.quiz_state = "idle"
            st.rerun()
    with c2:
        if st.button("🤖 Continue Tutoring", use_container_width=True):
            st.switch_page("pages/4_Tutor_Chat.py")
    with c3:
        if st.button("📈 View Dashboard", use_container_width=True):
            st.switch_page("pages/7_Dashboard.py")
